### ISSUE TITLE
Change order of post listing

### ISSUE THREAD

**Issue by Narven** [nurlansu/hugo-sustain#13]
How can I change the order of the listing of posts? Is showing from older to new... I want new to old.

thanks

**Comment by StevenMMortimer** [comment]
@Narven You should change [Line 10](https://github.com/nurlansu/hugo-sustain/blob/master/layouts/_default/list.html#L10) of `/layouts/_default/list.html`. 

Replace Line 10 with the following code to order from new to old based on the date of the article, not the date it was published: 

```
{{ range .Data.Pages.ByDate.Reverse }}
```
