### ISSUE TITLE
Changing the Opening statement

### ISSUE THREAD

**Issue by tristan-gardner** [nurlansu/hugo-sustain#16]
Hi and thanks for the theme.  The layout is great but I am having trouble figuring out how to change some features so that it flows better for my use.  Mainly I cannot change the front page description.  I'd like to remove some links and add some more lines but cannot figure out where this text is generated.  How do I get access to alter this paragraph?

Thanks

**Comment by nibalizer** [comment]
This threw me a bit too. Create a directory ``layouts`` in your root. Then copy ``themes/hugo-sustain/layouts/index.html``  to ``layouts/index.html`` in your root directory. Then just edit the file. It is html but it should be straightforward where to change the text. 

Hope this helps.

**Comment by tristan-gardner** [comment]
Perfect thank you

**Comment by suyundukov** [comment]
I’m not sure what I can do here. If you have any ideas or if you just would like to discuss this, please feel free to reopen.

**Comment by kishaningithub** [comment]
@nurlansu Why not fetch the about from `config.toml` ? 

Something like 

```toml
[params]
  about = """
       <h3>I'm <strong>{{ .Site.Params.author }}</strong>, a Software Engineer.</h3>
        <h3>I love all things computer science and maths.</h3>
        <h3>Have a look at some of my working <a href="{{ .Site.BaseURL }}projects/"> projects</a>.</h3>
        <h3>For more check out my academic &amp; professional <a href="https://demo.nurlan.co/hugo-vitae/">resume</a>.</h3>
        <h3>Contact me at <a href="http://twitter.com/{{ .Site.Params.Social.Twitter }}">@{{ .Site.Params.Social.Twitter }}</a> or by <a href="mailto:{{ .Site.Params.Social.Email }}">email</a>.</h3>
       """
```

But the catch here are these template strings `{{ .Site.Params.author }}` `{{ .Site.BaseURL }}` etc will be rendered as is.

I personally think because of this people can hard code whatever they they want in about page.

I feel this is better than making it non-customizable
