### ISSUE TITLE
Resume missing

### ISSUE THREAD

**Issue by raptox** [nurlansu/hugo-sustain#2]
Hey Chris,

the Resume page is missing ☹️ 
that was actually the coolest site that made me wanna use this theme.
Can you add it?

Thanks

**Comment by suyundukov** [comment]
Hi @raptox ,
For resume go to this [page](https://github.com/sumaxime/hugo-vitae). It's the resume theme for Hugo you asked for. Let me know if you need any help getting started.

**Comment by patrickderitter** [comment]
Hi @nurlansu, hopping in on an old issue here. Could you explain how these two themes should be working together? Would my /resume be an entire different hugo site?

**EDIT** found out how, linking it here: https://github.com/nurlansu/hugo-sustain/issues/7#issuecomment-303346897
